# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: cd mayan-edms |
          virtualenv venv |
          source venv/bin/activate |
          pip install -r requirements.txt
    command: ./manage.py runserver 8090

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 8090
    onOpen: open-preview
